# Generated by Django 3.0.8 on 2020-08-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200810_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fullName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='ProfileImage/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileSummary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
